---
- name: Create MySQL database for laravel
  mysql_db: name=laravel state=present

- name: Create MySQL user for laravel
  mysql_user: name=laravel password=laravel priv=*.*:ALL state=present

- name: Create PostgreSQL database for laravel
  sudo: yes
  sudo_user: postgres
  postgresql_db: name=laravel state=present

- name: init database user
  postgresql_user: name=laravel password=laravel db=symfony priv=ALL
  sudo: yes
  sudo_user: postgres

- name: psql check schema laravel
  command: psql -t -d symfony -c "SELECT EXISTS(SELECT 1 FROM pg_namespace WHERE nspname = 'laravel');"
  register: check_schema
  changed_when: "'f' in '{{ check_schema.stdout }}'"
  sudo: yes
  sudo_user: postgres

- name: psql schema laravel
  command: psql -d laravel -c "CREATE SCHEMA laravel; ALTER USER laravel SET search_path TO laravel;"
  when: check_schema.changed
  sudo: yes
  sudo_user: postgres

- name: psql grant access to schema laravel to all
  postgresql_privs: database=laravel type=schema objs=laravel roles=PUBLIC privs=USAGE
  sudo: yes
  sudo_user: postgres

- name: psql grant access to tables of schema laravel
  postgresql_privs: database=laravel schema=laravel type=table objs=ALL_IN_SCHEMA roles=PUBLIC privs=SELECT
  sudo: yes
  sudo_user: postgres

- name: Clone Laravel quickstart application
  git: repo=https://github.com/laravel/quickstart-basic
       dest=/vagrant/laravel-quickstart
       update=no
  become: true
  become_user: "{{ www_user }}"

- name: Copy across new .env file
  template:
    src=.env.j2
    dest=/vagrant/laravel-quickstart/.env
  become: true
  become_user: "{{ www_user }}"

- name: Install Laravel project dependencies
  shell: cd /vagrant/laravel-quickstart && COMPOSER_PROCESS_TIMEOUT={{composer_process_timeout}} composer install
  become: true
  become_user: "{{ www_user }}"

- name: Generate laravel key
  shell: cd /vagrant/laravel-quickstart && php artisan key:generate
  become: true
  become_user: "{{ www_user }}"

- name: Execute migrations for the quickstart example
  shell: cd /vagrant/laravel-quickstart && php artisan migrate
  become: true
  become_user: "{{ www_user }}"

- name: Copy across new php-fpm pool config for laravel
  template:
    src=php-fpm.conf.j2
    dest=/etc/php/{{ php_version }}/fpm/pool.d/laravel.conf
  notify:
    - restart php-fpm

- name: Copy across new virtual host for laravel
  template:
    src=nginx.conf.j2
    dest=/etc/nginx/sites-available/laravel.conf
  notify:
    - restart nginx

- name: Enable new vagrant virtual host for laravel
  file:
    src=/etc/nginx/sites-available/laravel.conf
    dest=/etc/nginx/sites-enabled/laravel.conf
    state=link
  notify:
    - restart nginx
