---
- name: Create MySQL database for CakePHP
  mysql_db: name=cakephp state=present

- name: Create MySQL user for CakePHP
  mysql_user: name=cakephp password=cakephp priv=*.*:ALL state=present

- name: Install CakePHP
  shell: cd /vagrant && composer create-project --prefer-dist cakephp/app cakephp
  become: true
  become_user: "{{ www_user }}"

- name: Remove default CakePHP app.php
  file:
    path=/vagrant/cakephp/config/app.php
    state=absent

- name: Copy across new parameters.yml
  template:
    src=app.php.j2
    dest=/vagrant/cakephp/config/app.php
  become: true
  become_user: "{{ www_user }}"

- name: Copy across new php-fpm pool config for CakePHP
  template:
    src=php-fpm.conf.j2
    dest=/etc/php/{{ php_version }}/fpm/pool.d/cakephp.conf
  notify:
    - restart php-fpm

- name: Copy across new virtual host for CakePHP
  template:
    src=nginx.conf.j2
    dest=/etc/nginx/sites-available/cakephp.conf
  notify:
    - restart nginx

- name: Enable new vagrant virtual host for cakephp
  file:
    src=/etc/nginx/sites-available/cakephp.conf
    dest=/etc/nginx/sites-enabled/cakephp.conf
    state=link
  notify:
    - restart nginx
