---
- name: Install nginx
  apt: name=nginx state=present

- name: Copy across new nginx config
  template:
    src=nginx.conf.j2
    dest=/etc/nginx/nginx.conf
  notify:
    - restart nginx

- name: Remove default virtual host
  file:
    path=/etc/nginx/sites-enabled/default
    state=absent
  notify:
    - restart nginx

- name: Copy across OpenSSL Script
  template:
    src=create_ssl.sh.j2
    dest=/vagrant/create_ssl.sh

- name: Sign Certificate
  script: /vagrant/create_ssl.sh
  notify:
    - restart nginx
    
- name: Remove default virtual host
  file:
    path=/vagrant/create_ssl.sh
    state=absent
